### ISSUE TITLE
[ngrx-ducks] Simplify API with Decorators

### ISSUE THREAD

**Issue by GregOnNet** [co-IT/co-it#3]
The following code is experimental.
It shows how a wired action could be created using a decorator.
In this way, we could get rid of the factory function `wireUpActions`.

## 🥇API

```ts
// Define
@InitialState<number>(0)
class CounterDuck {
  @Action('increment')
  increment(state: number): number {
    return state++;
  }
}

// Usage
export class SomeComponent {
 constructor(@Inject(Counter) private counter: Duck<Counter>) {}
}
```

## ToDo

- [x] **Action** Decorator
- [x] **InitialState** Decorator

**Comment by GregOnNet** [comment]
The progress of this enhancement can be observed in the branch [ducks/decorators](https://github.com/co-IT/co-it/tree/ducks/decorators).

## State as Is

- 🚀 I accomplished to generate a so-called `WiredAction` with a decorator
- 🚀 TypeSafety also seems to work

## Open Questions

- [x] How to handle multiple action types (`@Action(['increase', 'add'])`)
- [x] How to create Ducks-Service
- [x] How to create reducer function

## Hopes

We potentially end up with a solution allowing us to work with pure class Tokens.
This would simplify the way to register ducks as services in Angular.
Maybe we can use the following API in future:

```ts
@NgModule({
  imports: [DucksModule.register([Orders, User, Errors])]
})
```

> ⚠️**Notice** the shown code is highly experimental and not evaluated yet.

## [UPDATE]

`DucksModule` is not possible due to `AoT` restrictions.
We need to add our own provider for each duck.
Schematics will automate this task.

**Comment by skydever** [comment]
hi!

This looks very good 👍  Can't wait to see this released.

I created a workspace schematic inside a @nrwl/nx workspace that creates a new module looking like this (Some schematics would be great, I can share this one if you like or contribute maybe. Do you have any plans on schematics yet?):

```
.
+-- feature
|   +-- components
|   +-- container
|   +-- models
|   +-- services
|     +-- feature.service.ts
|   +-- store
|     +-- effects
|       +-- feature.effects.ts
|     +-- reducer
|       +-- feature.duck.ts
|       +-- index.ts
|     +-- selectors
|       +-- index.ts
|   +-- feature.module.ts
```

The `index.ts` file within the `selectors` directory is exporting a `fromFeature` object containing all the selectors, mainly to get the IDE to auto import it correctly. Not sure about downsides doing it that way. I saw that this is usually done at the import statement itself  like this `import * as fromFeature from '...';`

What do you think about it? I got the idea from your [keep](https://github.com/GregOnNet/keep) repository and the great talk you gave at an [Angular Graz](https://www.meetup.com/de-DE/Angular-Meetup-Graz/) meetup.

**Comment by GregOnNet** [comment]
Hi!

Thanks for the feedback.
Schematics are definitely on the road map.
I created an issue for it yet: https://github.com/co-IT/co-it/issues/5

Instead of generating the whole directory structure, I want to go for generating the Duck only.
So every team can go for its own directory structure the app.

Since I am ready with the *Decorators* we can move on with the Schematics.
I would appreciate your help!

Can I reach out to you when I am done with this issue?

**Comment by GregOnNet** [comment]
For now, we plan a major release for this feature, since it costs too much effort to support two APIs creating a Duck-Service.

~At the moment this feature will land in **ngrx-ducks@8.0.0**.~

**UPDATE**

The Decorator API will be shipped with a minor release.
This adds the possibility for teams already using Ducks to migrate in their own time. 🤗

**Comment by GregOnNet** [comment]
I created a PR for this issue #6.
It is easier to keep track of the work we put into this feature. :)

The snippet below shows the current state of the API.

## Duck itself

```ts
@InitialState({ isLoading: false })
export class GlobalLoadingIndicator {
  @Action('load')
  load(state: LoadingState) {
    return { ...state, isLoading: true};
  }

  @Action('finish')
  finish(state: LoadingState) {
    return { ...state, isLoading: false};
  }

  /*
   * To model different action types triggering the same case reducer
   * a Duck allows to reuse other class methods.
   */
  @Action('busyAgain')
  busyAgain(state: LoadingState) {
    return this.load(state);
  }

}
```

## Create Reducer

```ts
const reducer = reducerFrom(GlobalLoadingIndicator);
```

**Comment by skydever** [comment]
The API looks really great 👍 

Do you plan a release soon? 

Can you provide a `@next` version on npm maybe? It would make it a bit easier to try it out. Then I can run some tests and post results if it would help.

**Comment by GregOnNet** [comment]
Hopefully, I release the `@next` version this evening. 💪

**Comment by skydever** [comment]
Awesome 👍 I will try it out and post some results!

**Comment by GregOnNet** [comment]
I did a release yesterday.
But it is highly experimental.

I now add the possibility to use `.pick` and `effect`.
Today there will be a new release.

Unfortunately, it is not possible to introduce a `DucksModule.register` API.
AoT simply does not allows it.

This has an impact of the discussion concerning schematics.

**Comment by GregOnNet** [comment]
Version `7.3.1-alpha.2` has been released.
I managed to migrate my little sample App to the decorator API 🎉 .

See https://github.com/gregonnet/ngrx-ducks-demo

**Comment by GregOnNet** [comment]
Hi @skydever,

You can have a look at #6.
The hardest part is done.
I need to clean up some things.
Besides that, I feel that the API is ready now to be tested.

**Comment by GregOnNet** [comment]
@skydever fyi, I recently published the beta release.

**Comment by skydever** [comment]
great, thx! I was able to test the latest alpha version with no changes in my code - and everything was still working 👍 sadly something came up and I had to stop the migration to the decorator API, but I can give results on monday.

... and I came across one thing I wanted to create an issue for, but it seems to be fixed with the new decorator API. If you create an action without payload, you had to pass an empty object to the action method call. With the new decorator API this seems not to be required anymore, I even get typescript errors at the method calls now - after I removed the empty object I passed to the method the typescript error is gone, but I could not test the execution yet. As said before, I can give more results on monday.

**Comment by GregOnNet** [comment]
Thank you,

I leave this issue open until everything works for you.

**Comment by GregOnNet** [comment]
I published version 7.3.1-beta.2 introducing a new feature.
You can now directly access the `action type` of a self-dispatching action.
This might be useful if you want to use it in an Effect.

```ts
// counter.duck.ts
@IntiialState({ /* ... */ })
export class Counter {
  @Action('[Counter] Decrement value')
  decrement(state: CounterState, payload: number): CounterState {
    return {
      ...state,
      count: state.count - payload
    };
  }
}

// some.component.ts
/* ... */
decrement() {
  this.counter.decrement(1); // Dispatches action
  console.log(this.counter.decrement.type); // logs "[Counter] Decrement value"
}
```

**Comment by skydever** [comment]
The new feature is great, ngrx also does not differ between EffectActions and simple Actions - but having the option to explicitly define `effect`s (effect properties) is a bonus on top of it and I will still take advantage of it. By defining effect properties you see immediately that it is an effect (the triggering is different), totally helps if you look at existing code ...

... but I also have a use case for the new feature, the exception for me to mix it. I have to create an effect that catches actions from multiple ducks, not a concern of a single duck, and this is now possible without changing every action to an effect property (+effect, +additional action to do the original state mutation) 👍

**Comment by skydever** [comment]
Today I converted the `Ducks` to the new decorator API and all tests passed, looks fine to me 👍 

As mentioned previously, I don't have to pass an empty payload object to self dispatching action methods anymore if they do not have a payload - which is great!

**Comment by GregOnNet** [comment]
Thank you for the feedback.
I will release the final version this evening.

In version `7.3.1` also #9 will be covered. 👌
